version: '2'
services: 
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3010:3000"
    depends_on: 
      - "prometheus"
    environment: 
      - "GF_SECURITY_ADMIN_PASSWORD=secret"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes: 
    - "./config/prometheus.yml:/etc/prometheus/prometheus.yml"